// Auto-generated by scripts/assets/audit-preop-icons.mjs
export const manifest: Record<string, string> = {
  "seatbeltReminder": "training/d1-seatbelt.svg",
  "ppeVest": "training/c1-ppe-vest.svg",
  "ppeHardhat": "training/c1-ppe-hardhat.svg",
  "ppeBoots": "training/c1-ppe-boots.svg",
  "ppeGoggles": "training/c1-ppe-goggles.svg",
  "controlHorn": "training/c3-control-horn.svg",
  "controlLights": "training/c3-control-lights.svg",
  "dataPlate": "training/c5-plate.svg"
};
export function resolveAsset(key: string, fallbackPath?: string) {
  return manifest[key] || fallbackPath || key;
}
