/**
 * Build CPA glass intake CSV/JSON + phase lists from structured QRG data.
 *
 * Source: 2110094T CPA Windshields and Glass Product Catalog
 * Usage: npx tsx scripts/glass/build-cpa-glass-intake.ts
 */

import fs from 'fs';
import path from 'path';

type GlassRow = {
  vendor_pn: string;
  brand: string;
  glass_type: string;
  material: string;
  color: string;
  thickness_mm: number | null;
  max_width_mm: number | null;
  min_width_mm: number | null;
  height_mm: number | null;
  hole_count: number | null;
  compatible_models: string[];
  is_pack?: boolean;
  pack_qty?: number;
  phase: string;
  notes?: string;
  is_accessory?: boolean;
};

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function oemDisplay(vendorPn: string, brand: string): string {
  const pn = vendorPn.trim();
  if (brand === 'Cab Glass Accessory') {
    // House accessory catalog codes use SY prefix — strip for customer display.
    if (pn.toUpperCase().startsWith('SY')) return pn.slice(2);
    return pn;
  }
  if (pn.startsWith('KB')) return pn.slice(2);
  if (pn.startsWith('BC')) return pn.slice(2);
  if (pn.startsWith('CT')) return pn.slice(2);
  if (pn.startsWith('CS')) return pn.slice(2);
  if (pn.startsWith('JD')) return pn.slice(2);
  if (pn.startsWith('TK')) return pn.slice(2);
  return pn;
}

function brandSlug(brand: string): string {
  if (brand === 'Cab Glass Accessory') return 'glass';
  if (brand === 'John Deere') return 'john-deere';
  return slugify(brand);
}

function typeSlug(glassType: string): string {
  return slugify(glassType.replace(/_/g, '-'));
}

function buildSlug(row: GlassRow): string {
  const oem = oemDisplay(row.vendor_pn, row.brand).toLowerCase();
  const oemSlug = slugify(oem);
  if (row.is_accessory) {
    return `${typeSlug(row.glass_type)}-${oemSlug}`;
  }
  return `${brandSlug(row.brand)}-${oemSlug}-${typeSlug(row.glass_type)}`;
}

const ROWS: GlassRow[] = [
  // ── Phase 1 Accessories ──────────────────────────────────────────
  {
    vendor_pn: 'BC7281063',
    brand: 'Bobcat',
    glass_type: 'door_seal',
    material: 'seal',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T770', 'T870',
    ],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'BC6554149',
    brand: 'Bobcat',
    glass_type: 'window_cord',
    material: 'cord',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: [
      '463', '553AF', '632', '751', '753', '773', 'S100', 'S130', 'S175', 'S185', 'S220',
      'S250', 'S300', 'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'S70',
      'T110', 'T190', 'T250', 'T300', 'T450', 'T550', 'T590', 'T630', 'T650', 'T740', 'T750',
      'T770', 'T870',
    ],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'BC6665568',
    brand: 'Bobcat',
    glass_type: 'bulk_seal',
    material: 'seal',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: [
      '463', '553AF', '753', '763', '773', 'S100', 'S130', 'S175', 'S185', 'S220', 'S250',
      'S300', 'S70', 'T110', 'T190', 'T250', 'T300',
    ],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'SY1261845',
    brand: 'Cab Glass Accessory',
    glass_type: 'glass_adhesive',
    material: 'adhesive',
    color: 'black',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: [],
    phase: '1',
    is_accessory: true,
    notes: '10.5oz/310ml polyurethane glass adhesive; cures in 24 hours',
  },
  {
    vendor_pn: 'SY84151PEN',
    brand: 'Cab Glass Accessory',
    glass_type: 'glass_cleaner',
    material: 'cleaner',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: [],
    phase: '1',
    is_accessory: true,
    notes: '19oz/562ml ammonia-free foaming glass cleaner',
  },
  {
    vendor_pn: 'BC7234369',
    brand: 'Bobcat',
    glass_type: 'exit_decal',
    material: 'decal',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: ['S100', 'S130', 'S175', 'S185', 'S70', 'T110', 'T190'],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'BC7157893',
    brand: 'Bobcat',
    glass_type: 'door_gas_spring',
    material: 'hardware',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: ['S100', 'S130', 'S175', 'S185', 'T110', 'T190'],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'TK16546-15220',
    brand: 'Takeuchi',
    glass_type: 'seal',
    material: 'seal',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: ['TB016'],
    phase: '1',
    is_accessory: true,
  },
  {
    vendor_pn: 'TK16540-11520',
    brand: 'Takeuchi',
    glass_type: 'door_handle',
    material: 'hardware',
    color: '',
    thickness_mm: null,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: null,
    compatible_models: ['TL10', 'TL12', 'TL230', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '1',
    is_accessory: true,
  },

  // ── Phase 2 Bobcat ───────────────────────────────────────────────
  {
    vendor_pn: 'BC7120401',
    brand: 'Bobcat',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 805,
    min_width_mm: 295,
    height_mm: 1065,
    hole_count: 11,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T770', 'T870',
    ],
    phase: '2',
    notes: 'DOT certified',
  },
  {
    vendor_pn: 'BC7120401PK',
    brand: 'Bobcat',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 805,
    min_width_mm: 295,
    height_mm: 1065,
    hole_count: 11,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T770', 'T870',
    ],
    is_pack: true,
    pack_qty: 25,
    phase: '2',
  },
  {
    vendor_pn: 'BC6729776',
    brand: 'Bobcat',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 680,
    min_width_mm: 295,
    height_mm: 880,
    hole_count: 3,
    compatible_models: [
      '753', 'S100', 'T110', 'S130', 'T140', 'S150', 'S160', 'S175', 'T180', 'S185',
      'T190', 'S205', 'S220', 'S250', 'T250', 'S300', 'T320',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC6729776PK',
    brand: 'Bobcat',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 680,
    min_width_mm: 295,
    height_mm: 880,
    hole_count: 3,
    compatible_models: [
      '753', 'S100', 'T110', 'S130', 'T140', 'S150', 'S160', 'S175', 'T180', 'S185',
      'T190', 'S205', 'S220', 'S250', 'T250', 'S300', 'T320',
    ],
    is_pack: true,
    pack_qty: 25,
    phase: '2',
  },
  {
    vendor_pn: 'BC7179045',
    brand: 'Bobcat',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 755,
    min_width_mm: 320,
    height_mm: null,
    hole_count: 3,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006172',
    brand: 'Bobcat',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 805,
    min_width_mm: 495,
    height_mm: null,
    hole_count: 0,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006077',
    brand: 'Bobcat',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 840,
    min_width_mm: 770,
    height_mm: 775,
    hole_count: 0,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7209964',
    brand: 'Bobcat',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 705,
    min_width_mm: null,
    height_mm: 835,
    hole_count: 14,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7178678',
    brand: 'Bobcat',
    glass_type: 'front_upper_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 705,
    min_width_mm: null,
    height_mm: 840,
    hole_count: 0,
    compatible_models: ['E32'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7170287',
    brand: 'Bobcat',
    glass_type: 'left_rear_side',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 765,
    min_width_mm: 390,
    height_mm: 415,
    hole_count: 0,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7266740',
    brand: 'Bobcat',
    glass_type: 'left_sliding_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 400,
    min_width_mm: null,
    height_mm: 465,
    hole_count: 1,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7003481',
    brand: 'Bobcat',
    glass_type: 'left_sliding_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 575,
    min_width_mm: 380,
    height_mm: 775,
    hole_count: 0,
    compatible_models: [
      '751', '753', '763', '773', 'S130', 'S175', 'S185', 'S220', 'S250', 'S300', 'T190',
      'T250', 'T300',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006014',
    brand: 'Bobcat',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 580,
    min_width_mm: 460,
    height_mm: null,
    hole_count: 0,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7170289',
    brand: 'Bobcat',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 530,
    min_width_mm: 445,
    height_mm: 540,
    hole_count: 0,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7261608',
    brand: 'Bobcat',
    glass_type: 'lower_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 365,
    min_width_mm: null,
    height_mm: 820,
    hole_count: 0,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7219974',
    brand: 'Bobcat',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 670,
    min_width_mm: null,
    height_mm: 400,
    hole_count: 0,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S630', 'S650', 'S750',
      'T450', 'T550', 'T590', 'T630', 'T650', 'T740', 'T750', 'T770', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7170288',
    brand: 'Bobcat',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 700,
    min_width_mm: null,
    height_mm: 625,
    hole_count: 0,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC6717874',
    brand: 'Bobcat',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 655,
    min_width_mm: 500,
    height_mm: 370,
    hole_count: 0,
    compatible_models: [
      '751', '753', '763', '773', '963', 'S100', 'S130', 'S175', 'S185', 'S220', 'S250',
      'S300', 'T110', 'T190', 'T250', 'T300',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006782',
    brand: 'Bobcat',
    glass_type: 'right_front_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 570,
    min_width_mm: 470,
    height_mm: 795,
    hole_count: 2,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC6691003',
    brand: 'Bobcat',
    glass_type: 'right_rear_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 809,
    min_width_mm: 646,
    height_mm: 835,
    hole_count: 0,
    compatible_models: ['963', 'S100', 'S130', 'S175', 'S185', 'S300', 'T110', 'T190'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7261610',
    brand: 'Bobcat',
    glass_type: 'right_sliding_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 400,
    min_width_mm: null,
    height_mm: 470,
    hole_count: 1,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7003482',
    brand: 'Bobcat',
    glass_type: 'right_sliding_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 575,
    min_width_mm: 380,
    height_mm: 775,
    hole_count: 0,
    compatible_models: ['S175', 'S185', 'S300', 'T110', 'T190'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7105034',
    brand: 'Bobcat',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 510,
    min_width_mm: 275,
    height_mm: 295,
    hole_count: 4,
    compatible_models: ['963', 'S100', 'S130', 'S175', 'S185', 'T110', 'T190'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006173',
    brand: 'Bobcat',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 7,
    max_width_mm: 925,
    min_width_mm: null,
    height_mm: 365,
    hole_count: 0,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7180309',
    brand: 'Bobcat',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 675,
    min_width_mm: null,
    height_mm: 380,
    hole_count: 0,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7006174',
    brand: 'Bobcat',
    glass_type: 'side_behind_door',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 540,
    min_width_mm: 520,
    height_mm: 820,
    hole_count: 1,
    compatible_models: ['E63', 'E85'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7155308',
    brand: 'Bobcat',
    glass_type: 'heavy_duty_door',
    material: 'polycarbonate',
    color: 'clear',
    thickness_mm: 13,
    max_width_mm: 805,
    min_width_mm: null,
    height_mm: 1063,
    hole_count: 10,
    compatible_models: ['M Series'],
    phase: '2',
    notes: 'Heavy duty polycarbonate door',
  },
  {
    vendor_pn: 'BC7266739',
    brand: 'Bobcat',
    glass_type: 'left_rear_fixed',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 445,
    min_width_mm: null,
    height_mm: 470,
    hole_count: 0,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC6691001',
    brand: 'Bobcat',
    glass_type: 'left_rear_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 646,
    min_width_mm: null,
    height_mm: 809,
    hole_count: 0,
    compatible_models: ['963', 'S100', 'S130', 'S175', 'S185', 'S300', 'T110', 'T190'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7261609',
    brand: 'Bobcat',
    glass_type: 'right_rear_fixed',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 445,
    min_width_mm: null,
    height_mm: 470,
    hole_count: 0,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S650', 'T450', 'T550',
      'T590', 'T630', 'T650', 'T740', 'T750', 'T870',
    ],
    phase: '2',
  },
  {
    vendor_pn: 'BC7166468',
    brand: 'Bobcat',
    glass_type: 'right_side_fixed',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 265,
    min_width_mm: 260,
    height_mm: 320,
    hole_count: 0,
    compatible_models: ['E26', 'E32', 'E42', 'E50'],
    phase: '2',
  },
  {
    vendor_pn: 'BC7120411',
    brand: 'Bobcat',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 346,
    min_width_mm: null,
    height_mm: 636,
    hole_count: 4,
    compatible_models: [
      'S450', 'S510', 'S530', 'S550', 'S570', 'S590', 'S595', 'S630', 'S650', 'S750',
      'T450', 'T550', 'T590', 'T630', 'T650', 'T740', 'T750', 'T770', 'T870',
    ],
    phase: '2',
  },

  // ── Phase 3 Caterpillar ──────────────────────────────────────────
  {
    vendor_pn: 'CT345-6230',
    brand: 'Caterpillar',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 790,
    min_width_mm: null,
    height_mm: 1141,
    hole_count: 9,
    compatible_models: ['259D', '262D', '289D'],
    phase: '3',
    notes: 'DOT certified',
  },
  {
    vendor_pn: 'CT223-0609',
    brand: 'Caterpillar',
    glass_type: 'door_center_panel',
    material: 'layered',
    color: 'green',
    thickness_mm: 7,
    max_width_mm: 475,
    min_width_mm: 415,
    height_mm: 905,
    hole_count: 0,
    compatible_models: [
      '216B', '226B', '232B', '236B', '242B', '246B', '247B', '252B', '257B', '262B',
    ],
    phase: '3',
  },
  {
    vendor_pn: 'CT223-0612',
    brand: 'Caterpillar',
    glass_type: 'door_left_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 165,
    min_width_mm: 110,
    height_mm: 815,
    hole_count: 0,
    compatible_models: [
      '216B', '226B', '232B', '236B', '242B', '246B', '247B', '252B', '257B', '262B',
    ],
    phase: '3',
  },
  {
    vendor_pn: 'CT223-0610',
    brand: 'Caterpillar',
    glass_type: 'door_right_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 115,
    min_width_mm: 90,
    height_mm: 825,
    hole_count: 0,
    compatible_models: [
      '216B', '226B', '232B', '236B', '242B', '246B', '247B', '252B', '257B', '262B',
    ],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7919',
    brand: 'Caterpillar',
    glass_type: 'left_side',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 900,
    min_width_mm: 417,
    height_mm: null,
    hole_count: 0,
    compatible_models: ['305E2', '305E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7908',
    brand: 'Caterpillar',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 505,
    min_width_mm: 335,
    height_mm: 530,
    hole_count: 0,
    compatible_models: ['305E2'],
    phase: '3',
  },
  {
    vendor_pn: 'CT389-8682',
    brand: 'Caterpillar',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 565,
    min_width_mm: 235,
    height_mm: 575,
    hole_count: 0,
    compatible_models: ['308E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT142-9319',
    brand: 'Caterpillar',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 610,
    min_width_mm: null,
    height_mm: 365,
    hole_count: 0,
    compatible_models: [
      '216B', '226B', '232B', '236B', '242B', '246B', '247B', '252B', '257B', '262B',
    ],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7917',
    brand: 'Caterpillar',
    glass_type: 'right_side_fixed',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 500,
    min_width_mm: null,
    height_mm: 680,
    hole_count: 0,
    compatible_models: ['305E2', '305E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7916',
    brand: 'Caterpillar',
    glass_type: 'right_side_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 530,
    min_width_mm: 440,
    height_mm: 680,
    hole_count: 2,
    compatible_models: ['305E2', '305E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7911',
    brand: 'Caterpillar',
    glass_type: 'upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 910,
    min_width_mm: 690,
    height_mm: 725,
    hole_count: 3,
    compatible_models: ['305E2', '305E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT419-1289',
    brand: 'Caterpillar',
    glass_type: 'upper_windshield',
    material: 'layered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 830,
    min_width_mm: null,
    height_mm: 775,
    hole_count: 0,
    compatible_models: ['308E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT419-9586',
    brand: 'Caterpillar',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 440,
    min_width_mm: null,
    height_mm: 805,
    hole_count: 0,
    compatible_models: ['308E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT419-9589',
    brand: 'Caterpillar',
    glass_type: 'left_side',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: null,
    min_width_mm: null,
    height_mm: null,
    hole_count: 0,
    compatible_models: ['308E2 CR'],
    phase: '3',
  },
  {
    vendor_pn: 'CT428-7912',
    brand: 'Caterpillar',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 455,
    min_width_mm: null,
    height_mm: 717,
    hole_count: 4,
    compatible_models: ['305E2', '305E2 CR'],
    phase: '3',
  },

  // ── Phase 4 Case ─────────────────────────────────────────────────
  {
    vendor_pn: 'CS84344565',
    brand: 'Case',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 745,
    min_width_mm: null,
    height_mm: 1160,
    hole_count: 8,
    compatible_models: ['SR160', 'SR175'],
    phase: '4',
    notes: 'DOT certified',
  },
  {
    vendor_pn: 'CSKHN30460',
    brand: 'Case',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 750,
    min_width_mm: null,
    height_mm: 945,
    hole_count: 0,
    compatible_models: ['CX75C SR', 'CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CS84259722',
    brand: 'Case',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 205,
    min_width_mm: 175,
    height_mm: 285,
    hole_count: 0,
    compatible_models: ['SR160', 'TR270', 'TV380', 'TV450'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN31800',
    brand: 'Case',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 640,
    min_width_mm: 245,
    height_mm: 565,
    hole_count: 2,
    compatible_models: ['CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN30710',
    brand: 'Case',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 735,
    min_width_mm: null,
    height_mm: 550,
    hole_count: 0,
    compatible_models: ['CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN32020',
    brand: 'Case',
    glass_type: 'side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 1175,
    min_width_mm: 450,
    height_mm: 1320,
    hole_count: 0,
    compatible_models: ['CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN31670',
    brand: 'Case',
    glass_type: 'upper_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 345,
    min_width_mm: 285,
    height_mm: 705,
    hole_count: 0,
    compatible_models: ['CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN31680',
    brand: 'Case',
    glass_type: 'upper_door_slider_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 330,
    min_width_mm: 185,
    height_mm: 705,
    hole_count: 2,
    compatible_models: ['CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CSKHN30640',
    brand: 'Case',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 760,
    min_width_mm: null,
    height_mm: 420,
    hole_count: 0,
    compatible_models: ['CX75C SR', 'CX80C'],
    phase: '4',
  },
  {
    vendor_pn: 'CS47405929',
    brand: 'Case',
    glass_type: 'heavy_duty_door',
    material: 'polycarbonate',
    color: 'clear',
    thickness_mm: 13,
    max_width_mm: 864,
    min_width_mm: null,
    height_mm: 1092,
    hole_count: 9,
    compatible_models: ['SR', 'TR'],
    phase: '4',
    notes: 'Heavy duty polycarbonate door',
  },

  // ── Phase 5 John Deere ───────────────────────────────────────────
  {
    vendor_pn: 'JDT312628',
    brand: 'John Deere',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 800,
    min_width_mm: 470,
    height_mm: 1165,
    hole_count: 11,
    compatible_models: ['318D', '320D', '323E', '326E', '332E', '333E'],
    phase: '5',
  },
  {
    vendor_pn: 'JDT242807',
    brand: 'John Deere',
    glass_type: 'roof_glass',
    material: 'polycarbonate',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 525,
    min_width_mm: null,
    height_mm: 420,
    hole_count: 0,
    compatible_models: ['318D', '320D', '320E', '323E', '326E', '332E', '333E'],
    phase: '5',
  },
  {
    vendor_pn: 'JDT242805',
    brand: 'John Deere',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'clear',
    thickness_mm: 6,
    max_width_mm: 630,
    min_width_mm: null,
    height_mm: 390,
    hole_count: 0,
    compatible_models: ['318D', '320D', '320E', '323E', '326E', '332E', '333E'],
    phase: '5',
  },
  {
    vendor_pn: 'JDT313462',
    brand: 'John Deere',
    glass_type: 'heavy_duty_door',
    material: 'polycarbonate',
    color: 'clear',
    thickness_mm: 13,
    max_width_mm: 800,
    min_width_mm: 470,
    height_mm: 1165,
    hole_count: 11,
    compatible_models: ['D CAB'],
    phase: '5',
    notes: 'Heavy duty polycarbonate door',
  },
  {
    vendor_pn: 'JD4635163',
    brand: 'John Deere',
    glass_type: 'door_rear_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 235,
    min_width_mm: null,
    height_mm: 1450,
    hole_count: 0,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00000190',
    brand: 'John Deere',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 765,
    min_width_mm: null,
    height_mm: 520,
    hole_count: 0,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006272',
    brand: 'John Deere',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 805,
    min_width_mm: null,
    height_mm: 535,
    hole_count: 0,
    compatible_models: ['26G', '35G', '50G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00004958',
    brand: 'John Deere',
    glass_type: 'front_lower_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 805,
    min_width_mm: null,
    height_mm: 535,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JD4678909',
    brand: 'John Deere',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 745,
    min_width_mm: null,
    height_mm: 730,
    hole_count: 1,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006271',
    brand: 'John Deere',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 795,
    min_width_mm: null,
    height_mm: 850,
    hole_count: 1,
    compatible_models: ['26G', '35G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00004957',
    brand: 'John Deere',
    glass_type: 'front_upper_windshield',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 795,
    min_width_mm: null,
    height_mm: 850,
    hole_count: 1,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006278',
    brand: 'John Deere',
    glass_type: 'left_side_front',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 410,
    min_width_mm: 350,
    height_mm: 770,
    hole_count: 0,
    compatible_models: ['26G', '35G', '50G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006280',
    brand: 'John Deere',
    glass_type: 'left_side_rear',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 240,
    min_width_mm: 145,
    height_mm: 715,
    hole_count: 0,
    compatible_models: ['26G', '35G', '50G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00005004',
    brand: 'John Deere',
    glass_type: 'left_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 505,
    min_width_mm: null,
    height_mm: 860,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00000189',
    brand: 'John Deere',
    glass_type: 'lower_corner_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 560,
    min_width_mm: null,
    height_mm: 365,
    hole_count: 0,
    compatible_models: ['35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JD4635165',
    brand: 'John Deere',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 390,
    min_width_mm: 150,
    height_mm: 285,
    hole_count: 0,
    compatible_models: ['27D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006276',
    brand: 'John Deere',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 535,
    min_width_mm: null,
    height_mm: 530,
    hole_count: 0,
    compatible_models: ['26G', '35G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00004962',
    brand: 'John Deere',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 530,
    min_width_mm: 145,
    height_mm: 535,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JD4635162',
    brand: 'John Deere',
    glass_type: 'rear_corner_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 6,
    max_width_mm: 690,
    min_width_mm: 640,
    height_mm: 910,
    hole_count: 0,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JD4683794',
    brand: 'John Deere',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 965,
    min_width_mm: 410,
    height_mm: null,
    hole_count: 0,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00005006',
    brand: 'John Deere',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 840,
    min_width_mm: 640,
    height_mm: 625,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006282',
    brand: 'John Deere',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 565,
    min_width_mm: null,
    height_mm: 825,
    hole_count: 0,
    compatible_models: ['26G', '35G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDT251258',
    brand: 'John Deere',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 410,
    min_width_mm: null,
    height_mm: 960,
    hole_count: 4,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00004974',
    brand: 'John Deere',
    glass_type: 'side_lower_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 385,
    min_width_mm: 100,
    height_mm: 335,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00004960',
    brand: 'John Deere',
    glass_type: 'upper_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 500,
    min_width_mm: 430,
    height_mm: 700,
    hole_count: 0,
    compatible_models: ['60G'],
    phase: '5',
  },
  {
    vendor_pn: 'JDFYD00006274',
    brand: 'John Deere',
    glass_type: 'upper_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 515,
    min_width_mm: 430,
    height_mm: 705,
    hole_count: 0,
    compatible_models: ['26G', '35G'],
    phase: '5',
  },
  {
    vendor_pn: 'JD4635164',
    brand: 'John Deere',
    glass_type: 'upper_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 260,
    min_width_mm: 160,
    height_mm: 860,
    hole_count: 0,
    compatible_models: ['27D', '35D'],
    phase: '5',
  },

  // ── Phase 6 Kubota ───────────────────────────────────────────────
  {
    vendor_pn: 'KBRG158-46930',
    brand: 'Kubota',
    glass_type: 'upper_door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 610,
    min_width_mm: 480,
    height_mm: 910,
    hole_count: 0,
    compatible_models: ['KX018-4'],
    phase: '6',
    notes: 'DOT certified',
  },
  {
    vendor_pn: 'KBRG158-46310',
    brand: 'Kubota',
    glass_type: 'front_lower_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 720,
    min_width_mm: null,
    height_mm: 430,
    hole_count: 0,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRD451-46440',
    brand: 'Kubota',
    glass_type: 'front_lower_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 760,
    min_width_mm: 560,
    height_mm: 445,
    hole_count: 2,
    compatible_models: ['KX040-4', 'U35-4', 'U55-4', 'U48-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRD158-46770',
    brand: 'Kubota',
    glass_type: 'left_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 375,
    min_width_mm: null,
    height_mm: 760,
    hole_count: 0,
    compatible_models: ['U55-4', 'U48-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRG158-46510',
    brand: 'Kubota',
    glass_type: 'left_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 525,
    min_width_mm: 465,
    height_mm: 1100,
    hole_count: 1,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRD158-46570',
    brand: 'Kubota',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 555,
    min_width_mm: null,
    height_mm: 520,
    hole_count: 0,
    compatible_models: ['U55-4', 'U48-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRG158-46940',
    brand: 'Kubota',
    glass_type: 'lower_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 620,
    min_width_mm: 610,
    height_mm: 655,
    hole_count: 0,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRG158-46530',
    brand: 'Kubota',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 835,
    min_width_mm: 810,
    height_mm: 690,
    hole_count: 0,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRD158-46450',
    brand: 'Kubota',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 745,
    min_width_mm: null,
    height_mm: 695,
    hole_count: 0,
    compatible_models: ['U55-4', 'U48-4'],
    phase: '6',
    notes: 'QRG lists V48-4; mapped to U48-4',
  },
  {
    vendor_pn: 'KBRG158-46420',
    brand: 'Kubota',
    glass_type: 'right_lower_bottom',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 520,
    min_width_mm: 335,
    height_mm: 375,
    hole_count: 0,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRG158-46800',
    brand: 'Kubota',
    glass_type: 'right_side_window_back',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 600,
    min_width_mm: 565,
    height_mm: 890,
    hole_count: 2,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRG158-46700',
    brand: 'Kubota',
    glass_type: 'right_side_window_front',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 590,
    min_width_mm: 460,
    height_mm: 900,
    hole_count: 2,
    compatible_models: ['KX018-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBRD158-46560',
    brand: 'Kubota',
    glass_type: 'upper_door_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 445,
    min_width_mm: 170,
    height_mm: 815,
    hole_count: 0,
    compatible_models: ['KX040-4', 'U35-4', 'U55-4'],
    phase: '6',
  },
  {
    vendor_pn: 'KBV0511-33150',
    brand: 'Kubota',
    glass_type: 'rear_window',
    material: 'polycarbonate',
    color: 'clear',
    thickness_mm: 4,
    max_width_mm: 640,
    min_width_mm: null,
    height_mm: 285,
    hole_count: 0,
    compatible_models: ['SVL75-2', 'SVL90-2', 'SVL95-2S'],
    phase: '6',
  },

  // ── Phase 7 Takeuchi ─────────────────────────────────────────────
  {
    vendor_pn: 'TK03586-00076',
    brand: 'Takeuchi',
    glass_type: 'front_lower_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 885,
    min_width_mm: 535,
    height_mm: 500,
    hole_count: 0,
    compatible_models: ['TB230'],
    phase: '7',
    notes: 'DOT certified',
  },
  {
    vendor_pn: 'TK08808-65301',
    brand: 'Takeuchi',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 1140,
    min_width_mm: 700,
    height_mm: 830,
    hole_count: 4,
    compatible_models: ['TL10', 'TL12', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05686-39430',
    brand: 'Takeuchi',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 620,
    min_width_mm: 475,
    height_mm: 1385,
    hole_count: 2,
    compatible_models: ['TB125', 'TB135', 'TB145', 'TB175'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03586-00096',
    brand: 'Takeuchi',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 595,
    min_width_mm: 535,
    height_mm: 1495,
    hole_count: 2,
    compatible_models: ['TB230'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05586-03910',
    brand: 'Takeuchi',
    glass_type: 'door_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 595,
    min_width_mm: 535,
    height_mm: 1495,
    hole_count: 2,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03786-01610',
    brand: 'Takeuchi',
    glass_type: 'front_lower_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 855,
    min_width_mm: null,
    height_mm: 495,
    hole_count: 4,
    compatible_models: ['TB125', 'TB135', 'TB145', 'TB153FR', 'TB175'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05586-04210',
    brand: 'Takeuchi',
    glass_type: 'front_lower_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 885,
    min_width_mm: 535,
    height_mm: 500,
    hole_count: 0,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05686-00120',
    brand: 'Takeuchi',
    glass_type: 'front_upper_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 885,
    min_width_mm: null,
    height_mm: 945,
    hole_count: 1,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03586-00098',
    brand: 'Takeuchi',
    glass_type: 'front_upper_panel',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 885,
    min_width_mm: null,
    height_mm: 945,
    hole_count: 1,
    compatible_models: ['TB230'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03586-00077',
    brand: 'Takeuchi',
    glass_type: 'left_side_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 490,
    min_width_mm: 470,
    height_mm: 1315,
    hole_count: 1,
    compatible_models: ['TB230'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05586-04220',
    brand: 'Takeuchi',
    glass_type: 'left_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 490,
    min_width_mm: 470,
    height_mm: 1315,
    hole_count: 1,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03786-01400',
    brand: 'Takeuchi',
    glass_type: 'left_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 340,
    min_width_mm: 140,
    height_mm: 1385,
    hole_count: 1,
    compatible_models: ['TB125', 'TB135', 'TB145'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08808-65423',
    brand: 'Takeuchi',
    glass_type: 'lower_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 530,
    min_width_mm: 520,
    height_mm: 495,
    hole_count: 0,
    compatible_models: ['TL10', 'TL12', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08808-65103',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 800,
    min_width_mm: null,
    height_mm: 530,
    hole_count: 0,
    compatible_models: ['TL10', 'TL12', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08818-42002',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 800,
    min_width_mm: 510,
    height_mm: 580,
    hole_count: 0,
    compatible_models: ['TL230A', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03386-30820',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 820,
    min_width_mm: null,
    height_mm: 865,
    hole_count: 0,
    compatible_models: ['TB016', 'TB125', 'TB135', 'TB145'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03786-01900',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 815,
    min_width_mm: null,
    height_mm: 865,
    hole_count: 0,
    compatible_models: ['TB125', 'TB135', 'TB145'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03586-00142',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 828,
    min_width_mm: null,
    height_mm: 932,
    hole_count: 0,
    compatible_models: ['TB230'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05586-04230',
    brand: 'Takeuchi',
    glass_type: 'rear_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 829,
    min_width_mm: null,
    height_mm: 932,
    hole_count: 0,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05686-39530',
    brand: 'Takeuchi',
    glass_type: 'right_lower_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 360,
    min_width_mm: 310,
    height_mm: 380,
    hole_count: 0,
    compatible_models: ['TB125', 'TB135', 'TB145', 'TB175'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03586-00106',
    brand: 'Takeuchi',
    glass_type: 'right_side_front_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 675,
    min_width_mm: 515,
    height_mm: 760,
    hole_count: 2,
    compatible_models: ['TB230'],
    phase: '7',
  },
  {
    vendor_pn: 'TK05586-00096',
    brand: 'Takeuchi',
    glass_type: 'right_side_front_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 680,
    min_width_mm: 525,
    height_mm: 765,
    hole_count: 2,
    compatible_models: ['TB260'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03786-01320',
    brand: 'Takeuchi',
    glass_type: 'right_side_front_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 590,
    min_width_mm: 445,
    height_mm: 810,
    hole_count: 2,
    compatible_models: ['TB125', 'TB135', 'TB145', 'TB153FR'],
    phase: '7',
  },
  {
    vendor_pn: 'TK03786-01330',
    brand: 'Takeuchi',
    glass_type: 'right_side_rear_slider',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 810,
    min_width_mm: null,
    height_mm: 400,
    hole_count: 2,
    compatible_models: ['TB125', 'TB135', 'TB145'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08808-65104',
    brand: 'Takeuchi',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 735,
    min_width_mm: null,
    height_mm: 250,
    hole_count: 0,
    compatible_models: ['TL10', 'TL12', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08808-44003',
    brand: 'Takeuchi',
    glass_type: 'roof_glass',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 735,
    min_width_mm: null,
    height_mm: 250,
    hole_count: 0,
    compatible_models: ['TL230A', 'TL8'],
    phase: '7',
  },
  {
    vendor_pn: 'TK06986-03220',
    brand: 'Takeuchi',
    glass_type: 'heavy_duty_windshield',
    material: 'polycarbonate',
    color: 'clear',
    thickness_mm: 13,
    max_width_mm: 830,
    min_width_mm: 700,
    height_mm: 1140,
    hole_count: 4,
    compatible_models: ['TL250'],
    phase: '7',
    notes: 'Heavy duty polycarbonate windshield',
  },
  {
    vendor_pn: 'TK08818-61101',
    brand: 'Takeuchi',
    glass_type: 'upper_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 4,
    max_width_mm: 435,
    min_width_mm: 250,
    height_mm: 485,
    hole_count: 0,
    compatible_models: ['TL12', 'TL250'],
    phase: '7',
  },
  {
    vendor_pn: 'TK08808-65422',
    brand: 'Takeuchi',
    glass_type: 'upper_side_window',
    material: 'tempered',
    color: 'green',
    thickness_mm: 5,
    max_width_mm: 535,
    min_width_mm: 525,
    height_mm: 505,
    hole_count: 2,
    compatible_models: ['TL10', 'TL12', 'TL230A', 'TL240', 'TL250', 'TL8'],
    phase: '7',
  },
];

function humanType(glassType: string): string {
  return glassType
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function main() {
  const outDir = path.resolve(process.cwd(), 'data/glass');
  fs.mkdirSync(outDir, { recursive: true });

  const seen = new Set<string>();
  const intake = [];

  for (const row of ROWS) {
    if (seen.has(row.vendor_pn)) {
      console.warn(`Duplicate vendor_pn skipped: ${row.vendor_pn}`);
      continue;
    }
    seen.add(row.vendor_pn);

    const oem_pn_display = oemDisplay(row.vendor_pn, row.brand);
    const slug = buildSlug(row);
    const publish_status = row.is_pack ? 'skip_retail' : 'pending';
    const is_glass_accessory = Boolean(row.is_accessory);
    const confirm_freight = !is_glass_accessory && !row.is_pack;

    intake.push({
      vendor_pn: row.vendor_pn,
      brand: row.brand,
      oem_pn_display,
      slug,
      glass_type: row.glass_type,
      glass_type_label: humanType(row.glass_type),
      material: row.material,
      color: row.color,
      thickness_mm: row.thickness_mm,
      max_width_mm: row.max_width_mm,
      min_width_mm: row.min_width_mm,
      height_mm: row.height_mm,
      hole_count: row.hole_count,
      compatible_models: row.compatible_models,
      is_pack: Boolean(row.is_pack),
      pack_qty: row.pack_qty ?? null,
      phase: row.phase,
      publish_status,
      is_glass_accessory,
      confirm_freight,
      notes: row.notes ?? '',
    });
  }

  const phases: Record<string, string[]> = {};
  for (const item of intake) {
    if (item.publish_status === 'skip_retail') continue;
    if (!phases[item.phase]) phases[item.phase] = [];
    phases[item.phase].push(item.vendor_pn);
  }

  const csvHeader = [
    'vendor_pn',
    'brand',
    'oem_pn_display',
    'slug',
    'glass_type',
    'material',
    'color',
    'thickness_mm',
    'max_width_mm',
    'min_width_mm',
    'height_mm',
    'hole_count',
    'compatible_models',
    'is_pack',
    'pack_qty',
    'phase',
    'publish_status',
    'is_glass_accessory',
    'confirm_freight',
    'notes',
  ];

  const csvLines = [
    csvHeader.join(','),
    ...intake.map((r) =>
      [
        r.vendor_pn,
        r.brand,
        r.oem_pn_display,
        r.slug,
        r.glass_type,
        r.material,
        r.color,
        r.thickness_mm ?? '',
        r.max_width_mm ?? '',
        r.min_width_mm ?? '',
        r.height_mm ?? '',
        r.hole_count ?? '',
        `"${r.compatible_models.join('|')}"`,
        r.is_pack,
        r.pack_qty ?? '',
        r.phase,
        r.publish_status,
        r.is_glass_accessory,
        r.confirm_freight,
        `"${(r.notes || '').replace(/"/g, '""')}"`,
      ].join(',')
    ),
  ];

  fs.writeFileSync(path.join(outDir, 'cpa-glass-intake.json'), JSON.stringify(intake, null, 2));
  fs.writeFileSync(path.join(outDir, 'cpa-glass-intake.csv'), csvLines.join('\n') + '\n');
  fs.writeFileSync(path.join(outDir, 'cpa-glass-phases.json'), JSON.stringify(phases, null, 2));

  const readme = `# CPA Cab Glass Intake

Source: vendor QRG \`2110094T\` (Windshields and Glass Product Catalog).
Built by: \`npx tsx scripts/glass/build-cpa-glass-intake.ts\`

## Files

- \`cpa-glass-intake.csv\` / \`.json\` — one row per vendor PN
- \`cpa-glass-phases.json\` — vendor PNs per publish phase (excludes \`skip_retail\` packs)

## Prefix / slug rules

| Prefix | Brand | OEM display |
|--------|-------|-------------|
| BC | Bobcat | strip BC |
| CT | Caterpillar | strip CT |
| CS | Case | strip CS |
| JD | John Deere | strip JD |
| KB* | Kubota | strip leading KB |
| TK | Takeuchi | strip TK |
| SY* | Cab Glass Accessory | strip SY (vendor_pn keeps SY) |

## Publish status

- \`pending\` — eligible for site publish
- \`skip_retail\` — 25-packs (\`*PK\`); B2B only, not published to PDPs

## Phases

1. Accessories (seals, cord, adhesive, cleaner, hardware)
2. Bobcat
3. Caterpillar
4. Case
5. John Deere
6. Kubota
7. Takeuchi
`;

  fs.writeFileSync(path.join(outDir, 'README.md'), readme);

  const flagships = [
    'BC7120401',
    'CT345-6230',
    'CS84344565',
    'JDT312628',
    'KBRG158-46930',
    'TK03586-00076',
  ];

  console.log(`Wrote ${intake.length} rows to data/glass/`);
  console.log('Phase counts:', Object.fromEntries(
    Object.entries(phases).map(([k, v]) => [k, v.length])
  ));
  console.log('\nFlagship QA:');
  for (const pn of flagships) {
    const row = intake.find((r) => r.vendor_pn === pn);
    if (!row) {
      console.error(`  FAIL missing ${pn}`);
      continue;
    }
    console.log(
      `  OK ${pn} → ${row.slug} | oem=${row.oem_pn_display} | models=${row.compatible_models.length}`
    );
  }
}

main();